name: my first ci
on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master
      workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: test123
          IMAGE_TAG: ${{ github.sha }}
        run: aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 725652414192.dkr.ecr.us-east-1.amazonaws.com/test123 
      - name: change the Docker image name
        run: docker tag booking-portal-api:latest 725652414192.dkr.ecr.us-east-1.amazonaws.com/test123/tripscout-booking-api:latest
      - name: Push the image to ECR
        run: docker push 725652414192.dkr.ecr.us-east-1.amazonaws.com/test123/tripscout-booking-api:latest    
        
          
